
name: sachdientudemo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  page_flip: ^0.2.0
  cupertino_icons: ^1.0.8
  
  # Add these dependencies
  http: ^1.1.0
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  
  # For web platform
  webview_flutter_web: ^0.2.2+4
  
  # For image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.1
  

  

  
  # Permissions
  permission_handler: ^11.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
